version: '3.8'
services:
  db:
    image: postgres:alpine3.19
    restart: always
    container_name: url-shortener-db
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - path: .env
        required: true
    networks:
      - url-shortener
    volumes:
      - db:/var/lib/postgresql/data

  redis:
    image: redis:alpine3.19
    container_name: url-shortener-redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - url-shortener

  url-shortener-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: url-shortener-api
    ports:
      - '3001:3001'
    environment:
      - PORT=3001
    depends_on:
      - db
      - redis
    env_file:
      - .env
    networks:
      - url-shortener
networks:
  url-shortener:
    driver: bridge
volumes:
  db:
  redis_data:
